version: "3.7"
services:
  backend:
    build: nba-insider
    ports: 
    - '8080:8080'
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dbuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
